[tox]
envlist = py{312}-django{52}

[pycodestyle]
max-line-length = 120
exclude = .pyc,migrations

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = eventtracking.django.tests.settings
    PYTHONPATH = {toxinidir}/src
deps =
    django52: Django>=5.2,<5.3
    -r{toxinidir}/requirements/test.txt
commands =

    pytest --cov-report=html --cov-report term-missing --cov-branch -k 'not integration and not performance' --cov-fail-under=95 --cov=eventtracking
    pytest --verbose -s -k 'integration'
    pycodestyle src/eventtracking
    pylint --rcfile=pylintrc src/eventtracking
