[tox]
envlist = py312-django52
requires =
    tox-uv>=1

[pycodestyle]
max-line-length = 120
exclude = .pyc,migrations

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    ci
setenv =
    DJANGO_SETTINGS_MODULE = eventtracking.django.tests.settings
    PYTHONPATH = {toxinidir}/src
commands =

    pytest --cov-report=html --cov-report term-missing --cov-branch -k 'not integration and not performance' --cov-fail-under=95 --cov=eventtracking
    pytest --verbose -s -k 'integration'
    pycodestyle src/eventtracking
    pylint --rcfile=pylintrc src/eventtracking
